### ISSUE TITLE
Processing time

### ISSUE THREAD

**Issue by jkrauss1987** [homewsn/bsniffhub#3]
Hello, my Core i5 from 2017 needs about 5 minutes to process a pcap file of 2MB size. Is that normal? Is there a way to speed things up?
Thanks

**Comment by homewsn** [comment]
What task are you performing?
The 2MB pcap file is very large, that's probably 40-45 minutes of actual BLE traffic. But still, the main goal of bsniffhub is to connect BLE sniffers with Wireshark in real time.
Converting a pcap file to another pcap file is rather a minor task for bsniffhub, so to increase speed here you will need a simple single-threaded utility such as Crackle.

**Comment by jkrauss1987** [comment]
The 2MB file was sniffed in a few seconds. It was pcapng file format but if you save it as .pcap it is still 1,5MB. It has 27k frames. I already tried "crackle". It is very fast. The same file is decrypted in a second but it has two problems: length is changed but length field is not corrected and the CRC is not calculated. So the output of crackle cannot be used for Wireshark dissectors that lay on top of the L2CAP Layer because this Layer is not seen anymore. With your tool this is working fine :)

To your question: I use the decryption of LE Secure Connections with a known LTK.

While converting i observed the task manager a saw that the CPU time for the process is at 0% most of the time and sometimes at 0.5%.
Anyway... thanks for your work!

**Comment by homewsn** [comment]
27k frames in a few seconds! This is very interesting, I don’t have an example with such intensity. Could you give the pcap file itself as an example, unless, of course, it contains personal or other sensitive information for you? You can email it to me if you don't want to make it public.
If this is not possible, then could you answer a few questions:
- what PHY is used?
- what LL connection interval is used?
- what is the average number of packets transmitted per connection interval?
- what is LL payload length?
- what is ATT MTU size?

And the last question - what sniffer do you use to capture such traffic?

Thanks

**Comment by jkrauss1987** [comment]
Hi, 

i am probably not allowed to share the pcap file but I try to answer your questions. The 27k packets were in about one minute and not a few seconds. I have to correct that but it is still a lot of traffic. I recorded everything including the advertising packets of all devices around. And that are many in my lab. It is about 400 packets per second. When a certain connection of two devices is followed the packets are much less, about 50 per second. I send you a mail with details of that connection.

I am sniffing with an Nordic nRF52 series device.
Thanks

**Comment by homewsn** [comment]
Thank you for the detailed information.

**Comment by trentp-igor** [comment]
I see the same thing.  I think there is some flaw in the way the cli is designed that prevents it from running at full speed.  So it only processes packets at some fixed rate that is near real-time even though CPU is almost entirely idle.

Even cutting and pasting LTK into the CLI is slow to respond to the characters.

**Comment by homewsn** [comment]
Unfortunately, I don't have the time or a large enough pcap input file to investigate this issue yet. But as a test, you can try to reduce the idle time of the required threads yourself. This is done the same way for all required thread_xx.c files. For example, for thread_ble.c you can replace sleep(10) with sleep(1) [here](https://github.com/homewsn/bsniffhub/blob/master/src/thread_ble.c#L122).
You could even try replacing it with Sleep(0) for Windows or sched_yield() for Linux.

The next step that may help is to increase the priority of the required threads, but this also needs to be tried.

**Comment by trentp-igor** [comment]
This causes the LTK countdown in the cli to be super fast.

The method used to try to get messages from queues and then sleep looks unusual for multi-threaded programming.  I believe a common design would be to have the thread block when trying to get a message from a queue when there are no messages.  When another thread adds a message, then it wakes and receives it.

It looks like there are functions using a condition variable, like `msg_cond_get_first()`, which could work this way.  But nothing uses them.  Also these functions do not look like they will work as is.

**Comment by homewsn** [comment]
> This causes the LTK countdown in the cli to be super fast.

If you replace sleep(10) with sleep(1) in [thread_cli.c,](https://github.com/homewsn/bsniffhub/blob/master/src/cli/thread_cli.c#L637) then you need to replace 100 with 1000 in all seconds counting lines, for example, [here](https://github.com/homewsn/bsniffhub/blob/master/src/cli/thread_cli.c#L558), [here](https://github.com/homewsn/bsniffhub/blob/master/src/cli/thread_cli.c#L575) etc.

>  I believe a common design would be to have the thread block when trying to get a message from a queue when there are no messages.

You're probably right and a redesign is needed to improve performance, but I don't have the resources to do it in the near future.

**Comment by homewsn** [comment]
In general, the problem is solved. Decrypting [this 2.19 MB file](https://github.com/homewsn/bsniffhub/blob/master/examples/sc-justworks-ltk-064188355D35D1B9C29F31B5F3FD9480.pcapng) took about 20 seconds, including entering the LTK key. My CPU usage was around 8%. A greater reduction in processing time would require changing threads priority, but would result in higher CPU usage.
